server:
  port: 9527

#根据微服务名称进行动态路由的配置
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                     #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:                               #带着数据库的那个8001
        - id: payment_routh                 #路由的id 无固定要求，但是要求唯一，建议派和服务名称
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**

#固定写死的路由配置
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:                         #带着数据库的那个8001
#        - id: payment_routh           #路由的id 无固定要求，但是要求唯一，建议派和服务名称
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**    #断言，路径相匹配的进行路由
#
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka         #集群版本的eureka
