server:
  port: 80

#服务消费者注册到Eureka中
eureka:
  client:
    register-with-eureka: false
    service-url:
      #defaultZone: http://localhost:7001/eureka         #单机版本的eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka         #集群版本的eureka

#这是原来的 不好使 下面的才好使
#ribbon的超时时间
#ribbon:
#  ReadTimeOut: 5000      #建立连接所用时间
#  ConnectTimeOut: 5000    #建立连接后读取可用资源的时间

ribbon:
    httpclient:
      enabled: true
    MaxConnectionsPerHost: 500
    MaxTotalConnections: 2000
    ConnectTimeout: 60000
    ReadTimeout: 60000

feign:
  hystrix:
    enabled: true

